
ERROR_TIME: 2021-07-23 19:35:49,171
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 515
ERROR_NAME: name 'nlp' is not defined
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 509, in run_program
    tagged = tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 290, in tagger
    doc = nlp(s)
NameError: name 'nlp' is not defined
